# Generated by Django 3.1.7 on 2021-05-30 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('room_amount', models.IntegerField(default=0)),
                ('nickname', models.CharField(max_length=255)),
                ('added_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=250)),
                ('lesson_pattern', models.CharField(max_length=250)),
                ('weekly_plan', models.IntegerField()),
                ('monthly_plan', models.IntegerField()),
                ('total_lessons', models.IntegerField()),
                ('course_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('lesson_pattern', models.CharField(max_length=255)),
                ('lesson_type', models.CharField(max_length=255)),
                ('group_type', models.CharField(max_length=255)),
                ('month_amount', models.IntegerField()),
                ('monthly_fee', models.IntegerField()),
            ],
            options={
                'verbose_name': 'salary',
                'verbose_name_plural': 'salary',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('id_mumber', models.CharField(max_length=250)),
                ('register_date', models.DateField()),
                ('born_date', models.DateField()),
                ('document_type', models.CharField(max_length=250)),
                ('passport_id', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('workplace', models.CharField(max_length=250)),
                ('login', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('fired_date', models.DateField()),
                ('reason', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('lesson_pattern', models.CharField(max_length=255)),
                ('lesson_type', models.CharField(max_length=255)),
                ('group_type', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'timetable',
                'verbose_name_plural': 'timetable',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('id_code', models.CharField(max_length=20)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('born_date', models.DateField()),
                ('student_age', models.IntegerField()),
                ('document_type', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('free_time', models.CharField(max_length=150)),
                ('age_level', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('tel_number', models.CharField(max_length=20)),
                ('student_login', models.CharField(max_length=150)),
                ('student_password', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_building', to='settings.building')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('room_type', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=100)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_name', to='settings.building')),
            ],
        ),
    ]
