# Generated by Django 3.2 on 2021-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('lesson_pattern', models.CharField(max_length=255)),
                ('lesson_type', models.CharField(max_length=255)),
                ('group_type', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
            ],
        ),
    ]
