# Generated by Django 3.1.7 on 2021-05-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='settings.subject'),
        ),
    ]
