# Generated by Django 3.1.7 on 2021-05-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210530_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_name', to='settings.subject'),
        ),
    ]
